# Generated by Django 5.1.2 on 2024-11-01 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('nr', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField()),
                ('token', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadicaleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('basic_httpsauth_user', models.CharField(max_length=255)),
                ('basic_httpsauth_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='i.e. Work, Private', max_length=255)),
                ('usage_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='contacts/companies/', verbose_name='photo')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('google_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_contacts.googleaccount')),
                ('radicale_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_contacts.radicaleaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='middle name')),
                ('suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='suffix')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='nickname')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('photo', models.ImageField(blank=True, upload_to='contacts/person/', verbose_name='photo')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('google_resource_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('origin_internal_addressbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_contacts.addressbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('origin_google_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_contacts.googleaccount')),
                ('export_filter_groups', models.ManyToManyField(blank=True, to='django_contacts.persongroup')),
                ('export_radicale_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_contacts.radicaleaccount')),
                ('origin_radicale_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_contacts.radicaleaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.person')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.phone')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.usagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroupConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.persongroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.person')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.usagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.email')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.person')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.usagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddressConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.person')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.usagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PersonWebsiteConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.person')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_contacts.usagecategory')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_contacts.website')),
            ],
        ),
    ]
