# Generated by Django 5.1.2 on 2024-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='last_api_called',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
