# Generated by Django 5.1.2 on 2024-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_contacts', '0002_googleaccount_last_api_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='api_call_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
