# Generated by Django 5.1.2 on 2024-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_contacts', '0004_instantmessanger_person_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessanger',
            name='im_type',
            field=models.CharField(choices=[('skype', 'Skype'), ('icq', 'ICQ'), ('aim', 'AIM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nickname'),
        ),
    ]
