# Generated by Django 5.1.2 on 2024-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_contacts', '0005_alter_instantmessanger_im_type_alter_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('pager', 'Pager')], default='work', max_length=20),
        ),
    ]
