# Generated by Django 5.1.2 on 2024-11-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_contacts', '0006_phone_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
